### ISSUE TITLE
Final Project feedback

### ISSUE THREAD

**Issue by EmanHerawy** [dabinlee708/blockchain-developer-bootcamp-final-project#1]
Hey @dabinlee708  I'm checking your project for grading and it seems awesome but I have to pause due to missing the package.json file, Would you please add it to the repo file and let me , Tom or Coogan know so that we can resume the grading and send you the final feedback?

**Comment by dabinlee708** [comment]
Hi Team! I've just updated my repo with package.json. Please let me know if any issues!

**Comment by EmanHerawy** [comment]
Thank you @dabinlee708
